# Generated by Django 3.0.4 on 2020-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('profilePicture', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=40)),
                ('suitablegroup', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('image1', models.ImageField(upload_to='pics')),
                ('name1', models.CharField(max_length=40)),
                ('lengthofstay1', models.IntegerField()),
                ('description1', models.CharField(max_length=20000)),
                ('location1', models.CharField(max_length=200)),
                ('image2', models.ImageField(upload_to='pics')),
                ('name2', models.CharField(max_length=40)),
                ('lengthofstay2', models.IntegerField()),
                ('description2', models.CharField(max_length=20000)),
                ('location2', models.CharField(max_length=200)),
                ('image3', models.ImageField(upload_to='pics')),
                ('name3', models.CharField(max_length=40)),
                ('lengthofstay3', models.IntegerField()),
                ('description3', models.CharField(max_length=20000)),
                ('location3', models.CharField(max_length=200)),
                ('image4', models.ImageField(upload_to='pics')),
                ('name4', models.CharField(max_length=40)),
                ('lengthofstay4', models.IntegerField()),
                ('description4', models.CharField(max_length=20000)),
                ('location4', models.CharField(max_length=200)),
                ('image5', models.ImageField(upload_to='pics')),
                ('name5', models.CharField(max_length=40)),
                ('lengthofstay5', models.IntegerField()),
                ('description5', models.CharField(max_length=20000)),
                ('location5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('album', models.CharField(max_length=20)),
                ('extra', models.CharField(max_length=20)),
                ('offer', models.BooleanField(default=False)),
                ('cont', models.ImageField(upload_to='pics')),
                ('videofile', models.FileField(null=True, upload_to='videos', verbose_name='video_file')),
            ],
        ),
    ]
