# Generated by Django 3.0.4 on 2020-05-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_remove_package_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image2',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
