# Generated by Django 3.0.4 on 2020-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_package_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='lengthofstay1',
            field=models.IntegerField(null=True),
        ),
    ]
