# Generated by Django 3.0.4 on 2020-05-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_auto_20200506_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description1',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='image1',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name1',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
