# Generated by Django 3.0.4 on 2020-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20200518_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='pics')),
                ('location5', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
