# Generated by Django 3.0.4 on 2020-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location5',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
