# Generated by Django 3.0.4 on 2020-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20200518_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
