# Generated by Django 3.0.4 on 2020-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_remove_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='WiFifacility',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
