# Generated by Django 3.0.4 on 2020-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_hotel_wififacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
