# Generated by Django 3.0.4 on 2020-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_hotel_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='image4',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
