# Generated by Django 3.0.4 on 2020-05-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_auto_20200520_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
