# Generated by Django 3.0.4 on 2020-06-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_holidayspackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayspackage',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='lengthofstay4',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='lengthofstay5',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='location4',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='location5',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='holidayspackage',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='package',
            name='lengthofstay4',
        ),
        migrations.RemoveField(
            model_name='package',
            name='lengthofstay5',
        ),
        migrations.RemoveField(
            model_name='package',
            name='location4',
        ),
        migrations.RemoveField(
            model_name='package',
            name='location5',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name5',
        ),
    ]
