# Generated by Django 3.0.4 on 2020-05-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0, max_length=100)),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Mobileno', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Address2', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
            ],
        ),
    ]
