# Generated by Django 3.0.4 on 2020-05-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='order_id',
            new_name='booking_id',
        ),
    ]
