# Generated by Django 3.0.4 on 2020-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0002_auto_20200505_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
