# Generated by Django 3.0.4 on 2020-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0003_auto_20200506_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
