# Generated by Django 3.0.4 on 2020-05-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0004_auto_20200506_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='items_json',
        ),
    ]
