# Generated by Django 3.0.4 on 2020-05-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0005_remove_book_items_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='amount',
        ),
    ]
