# Generated by Django 3.0.4 on 2020-05-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0006_remove_book_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Firstname',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Lastname',
        ),
    ]
