# Generated by Django 3.0.4 on 2020-05-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0007_auto_20200520_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Mobileno',
            new_name='Phone',
        ),
    ]
