# Generated by Django 3.0.4 on 2020-06-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0009_hotelbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='airbook',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Address2', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('trip_type', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('depart_on', models.DateField()),
                ('Adult', models.CharField(max_length=30)),
                ('Children', models.CharField(max_length=30)),
                ('infact', models.CharField(max_length=30)),
                ('economy', models.CharField(max_length=30)),
            ],
        ),
    ]
