# Generated by Django 3.0.4 on 2020-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0010_airbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbook',
            name='from1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
