# Generated by Django 3.0.4 on 2020-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0011_airbook_from1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airbook',
            old_name='trip_type',
            new_name='One_Way',
        ),
        migrations.AddField(
            model_name='airbook',
            name='Bussiness',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbook',
            name='First',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbook',
            name='Premium_Economy',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbook',
            name='Round_Trip',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
