# Generated by Django 3.0.4 on 2020-06-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0015_auto_20200628_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='book',
            name='gender',
        ),
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
