# Generated by Django 3.0.4 on 2020-06-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0016_auto_20200629_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
