# Generated by Django 3.0.4 on 2020-06-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0017_auto_20200629_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbook',
            name='ACRooms',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='Adult',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='Children',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='City',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='NonACRooms',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='State',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='hotelbook',
            name='check_out_date',
        ),
        migrations.AddField(
            model_name='hotelbook',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelbook',
            name='amount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbook',
            name='hotelname',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
